---
- name: Set permissions on socket - owner
  lineinfile: "dest=/etc/php-fpm.d/www.conf state=present regexp='^;?listen.owner' line='listen.owner = {{ php_owner }}'"
  notify: restart php-fpm

- name: Set permissions on socket - group
  lineinfile: "dest=/etc/php-fpm.d/www.conf state=present regexp='^;?listen.group' line='listen.group = {{ php_group }}'"
  notify: restart php-fpm

- name: Set permissions on socket - mode
  lineinfile: "dest=/etc/php-fpm.d/www.conf state=present regexp='^;?listen.mode' line='listen.mode = 0660'"
  notify: restart php-fpm
  
- name: Set php_values
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: '^{{ item.param|replace("[", "\[")|replace("]", "\]") }} *?='
    insertafter: '^;{{ item.param|replace("[", "\[")|replace("]", "\]") }} *?='
    line: "{{ item.param }} = {{ item.value }}"
  with_items:
    - { param: 'php_value[session.save_path]', value: '/home/vagrant/session' }
    - { param: 'php_value[soap.wsdl_cache_dir]', value: '/home/vagrant/wsdlcache' }
  notify: restart php-fpm

- name: Creates directory /home/vagrant/session
  file: path=/home/vagrant/session state=directory owner=vagrant group=vagrant mode=0755

- name: Creates directory /home/vagrant/wsdlcache
  file: path=/home/vagrant/wsdlcache state=directory owner=vagrant group=vagrant mode=0755
