---
- name: Install xDebug
  sudo: yes
  apt: pkg=php5-xdebug state=latest

- name: configure xdebug
  template: src=xdebug.ini dest=/etc/php5/mods-available/xdebug.ini
  sudo: yes
  notify:
    - nginx restart
    - php restart
