---
- name: Install Nginx
  sudo: yes
  apt: pkg=nginx state=latest

- name: Change default nginx site
  sudo: yes
  template: src=localhost.conf dest=/etc/nginx/sites-available/default.conf
  notify:
    - nginx restart
    - php restart

- name: Remove default virtualhost
  sudo: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - nginx restart
    - php restart

- name: configure nginx
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  sudo: yes
  notify:
    - nginx restart
    - php restart

- name: configure fcgi
  template: src=fcgi.conf dest=/etc/nginx/fcgi_local.conf
  sudo: yes
  notify:
    - nginx restart
    - php restart
