---
- hosts: symfony
  become: yes
  become_method: sudo
  vars_files:
    - vars.yml
  roles:
    - server
    - geerlingguy.ntp
    - geerlingguy.nginx
    - geerlingguy.php
    - php-fpm-pool
    - geerlingguy.composer
    - geerlingguy.git
    - postgresql
    - php
    - app
