# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "IngussNeilands/centos7-blank"
  
  config.vm.hostname = "symfony"
  config.vm.define "symfony" do |bindb|
  end
  
  config.vm.synced_folder "../", "/vagrant"

  # VMWare Workstation
  config.vm.provider "vmware_workstation" do |v, override|
    override.ssh.insert_key = false
    override.vm.box = "bento/centos-7.2"
    override.vm.network "private_network", ip: "113.0.0.18"
    v.memory = 1536
    v.name = "symfony"
  end

  if Vagrant.has_plugin?("vagrant-hostsupdater")  
    config.hostsupdater.aliases = ["symfony.local"]
  else
    puts "installing vagrant-hostsupdater plugin is recommended"
  end

  # Enable provisioning with a shell script
  config.vm.provision "shell", inline: <<-SHELL
	# for VMWare box only
    sudo yum -y install http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    sudo yum -y install ansible
	# ntp
	sudo ansible-galaxy install geerlingguy.ntp
    # nginx
	sudo ansible-galaxy install geerlingguy.nginx
	# php
    sudo rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
    sudo ansible-galaxy install geerlingguy.php
	# composer
	sudo ansible-galaxy install geerlingguy.composer
	# git
	sudo ansible-galaxy install geerlingguy.git
	# redis
	sudo ansible-galaxy install geerlingguy.redis
  SHELL

  # Run Ansible from the Vagrant VM
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
	ansible.provisioning_path = "/vagrant/ansible"
	#ansible.verbose = true
  end  

end
