---
- name: Install unit file
  become: yes
  template:
    src: postgresql.service.j2
    dest: "/etc/systemd/system/postgresql.service"
    owner: "root"
    group: "root"
    mode: 0644  
  notify:
    - reload systemd
    - restart postgresql

- name: Ensure postgresql starts at boot time
  service:
    name=postgresql
    enabled=yes